import React, { useState } from 'react';
import { X, FileText, Download, Calendar, Mail, Clock, CheckCircle2, Filter, Layers, Sparkles } from 'lucide-react';
import { useLanguageTheme } from '../context/LanguageThemeContext';
import { useAuth } from '../context/AuthContext';

interface ReportGeneratorModalProps {
  onClose: () => void;
}

export const ReportGeneratorModal: React.FC<ReportGeneratorModalProps> = ({ onClose }) => {
  const { t } = useLanguageTheme();
  const { addAuditLog, currentTenant } = useAuth();

  const [reportCategory, setReportCategory] = useState<'SECURITY' | 'ATTENDANCE' | 'INVENTORY' | 'AUDIT'>('SECURITY');
  const [format, setFormat] = useState<'CSV' | 'PDF' | 'JSON'>('CSV');
  const [dateFrom, setDateFrom] = useState('2026-09-01');
  const [dateTo, setDateTo] = useState('2026-09-12');
  const [isExporting, setIsExporting] = useState(false);
  const [isScheduleOpen, setIsScheduleOpen] = useState(false);
  const [scheduleCron, setScheduleCron] = useState<'DAILY' | 'WEEKLY' | 'MONTHLY'>('DAILY');
  const [scheduleEmails, setScheduleEmails] = useState('security-ops@aman-logistics.com');
  const [exportedNotice, setExportedNotice] = useState<string | null>(null);
  const [includeAiBriefing, setIncludeAiBriefing] = useState(true);

  const handleExport = async () => {
    setIsExporting(true);
    setExportedNotice(null);

    let aiBriefingText = '';
    if (includeAiBriefing) {
      try {
        const aiRes = await fetch('/api/ai/daily-briefing', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            metrics: {
              reportCategory,
              dateFrom,
              dateTo,
              tenant: currentTenant.name,
            },
          }),
        });
        if (aiRes.ok) {
          const aiData = await aiRes.json();
          aiBriefingText = aiData.briefing || '';
        }
      } catch (e) {
        console.error('Failed to fetch AI briefing for report:', e);
      }
    }

    const filename = `CCTV_REPORT_${reportCategory}_${dateFrom}_to_${dateTo}.${format.toLowerCase()}`;
    
    // Generate download payload
    let content = '';
    if (format === 'CSV') {
      content = `Tenant,Category,DateFrom,DateTo,Status,GeneratedAt\n${currentTenant.name},${reportCategory},${dateFrom},${dateTo},VERIFIED,${new Date().toISOString()}\n\n"AI_EXECUTIVE_BRIEFING","${aiBriefingText.replace(/"/g, '""')}"`;
    } else if (format === 'JSON') {
      content = JSON.stringify({
        tenant: currentTenant.name,
        category: reportCategory,
        dateRange: { from: dateFrom, to: dateTo },
        generatedAt: new Date().toISOString(),
        compliance: "ISO-27001 / GDPR Tamper-Proof Audit Compliant",
        aiExecutiveBriefing: aiBriefingText,
        dataRowsCount: 142,
      }, null, 2);
    } else {
      // PDF text representation
      content = `--- AI CCTV SECURITY & OPERATIONS EXECUTIVE REPORT ---\nTenant: ${currentTenant.name}\nReport Type: ${reportCategory}\nDate Range: ${dateFrom} - ${dateTo}\nGenerated by: Aman AI Operations Agent\n\n=== AI EXECUTIVE BRIEFING ===\n${aiBriefingText}`;
    }

    const blob = new Blob([content], { type: format === 'JSON' ? 'application/json' : 'text/plain;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);

    addAuditLog(
      'EXPORT_REPORT',
      `Report: ${reportCategory}`,
      `تم تصدير تقرير ${reportCategory} بصيغة ${format} للفترة من ${dateFrom} إلى ${dateTo}`
    );

    setIsExporting(false);
    setExportedNotice(t(`تم تصدير التقرير وتحميل ملف ${filename} بنجاح!`, `Successfully generated & downloaded ${filename}!`));
  };

  const handleSaveSchedule = () => {
    addAuditLog(
      'EXPORT_REPORT',
      `Scheduler: ${reportCategory}`,
      `تفعيل جدولة التقارير التلقائية (${scheduleCron}) وإرسالها دورياً إلى: ${scheduleEmails}`
    );
    setExportedNotice(t('تم تفعيل جدول إرسال التقارير التلقائي بنجاح!', 'Automated scheduled delivery configured successfully!'));
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md overflow-y-auto">
      <div 
        id="report-generator-modal-dialog"
        className="relative w-full max-w-xl bg-slate-900 border border-slate-700/80 rounded-3xl shadow-2xl overflow-hidden flex flex-col my-8"
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-950/80">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-cyan-950 border border-cyan-800 text-cyan-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-100">
                {t('مركز تصدير وجدولة التقارير الذكية', 'Reports & Automated Scheduler Center')}
              </h2>
              <p className="text-xs text-slate-400">
                {t('توليد تقارير أمنية، حضور، ومخزون موثقة بصيغ PDF وExcel وCSV', 'Generate certified security, attendance & inventory reports')}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-slate-100 transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 flex flex-col gap-5 text-xs text-slate-300">
          {/* Report Category */}
          <div>
            <label className="text-xs font-semibold text-slate-200 block mb-2">
              {t('نوع ومجال التقرير:', 'Report Domain:')}
            </label>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
              {[
                { id: 'SECURITY', label: t('الأمن والسرقات', 'Security & Theft') },
                { id: 'ATTENDANCE', label: t('الحضور والانصراف', 'Attendance') },
                { id: 'INVENTORY', label: t('المخزون والرؤية', 'Inventory CV') },
                { id: 'AUDIT', label: t('سجلات التدقيق', 'Audit Trail') },
              ].map(cat => (
                <button
                  key={cat.id}
                  type="button"
                  onClick={() => setReportCategory(cat.id as any)}
                  className={`p-2.5 rounded-xl border font-semibold text-center transition cursor-pointer ${
                    reportCategory === cat.id
                      ? 'bg-cyan-600 text-white border-cyan-500 shadow-md'
                      : 'bg-slate-950 border-slate-800 text-slate-400 hover:text-slate-200'
                  }`}
                >
                  {cat.label}
                </button>
              ))}
            </div>
          </div>

          {/* Date Range Filters */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-xs text-slate-400 block mb-1">
                {t('من تاريخ (Date From):', 'Date From:')}
              </label>
              <input
                type="date"
                value={dateFrom}
                onChange={e => setDateFrom(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-slate-950 border border-slate-700 text-slate-200 focus:outline-none focus:border-cyan-500"
              />
            </div>
            <div>
              <label className="text-xs text-slate-400 block mb-1">
                {t('إلى تاريخ (Date To):', 'Date To:')}
              </label>
              <input
                type="date"
                value={dateTo}
                onChange={e => setDateTo(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-slate-950 border border-slate-700 text-slate-200 focus:outline-none focus:border-cyan-500"
              />
            </div>
          </div>

          {/* Format Selector */}
          <div>
            <label className="text-xs font-semibold text-slate-200 block mb-1.5">
              {t('صيغة التصدير المطلوبة:', 'Export Format:')}
            </label>
            <div className="flex items-center gap-3">
              {(['CSV', 'PDF', 'JSON'] as const).map(fmt => (
                <button
                  key={fmt}
                  type="button"
                  onClick={() => setFormat(fmt)}
                  className={`flex-1 py-2 rounded-xl border text-center font-mono font-bold transition cursor-pointer ${
                    format === fmt
                      ? 'bg-emerald-600 text-white border-emerald-500 shadow-md'
                      : 'bg-slate-950 border-slate-800 text-slate-400 hover:text-slate-200'
                  }`}
                >
                  {fmt}
                </button>
              ))}
            </div>
          </div>

          {/* AI Executive Briefing Inclusion Toggle */}
          <div className="p-3 rounded-2xl bg-purple-950/30 border border-purple-800/50 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-purple-400" />
              <div>
                <span className="text-xs font-semibold text-purple-200 block">
                  {t('تضمين الموجز التنفيذي الذكي (Gemini AI Executive Briefing)', 'Include Gemini AI Executive Briefing')}
                </span>
                <span className="text-[11px] text-slate-400">
                  {t('صياغة موجز تحليلي ذكي للمدير التنفيذي مرفق بالتقرير', 'Generates an executive-level analytical summary via Gemini')}
                </span>
              </div>
            </div>
            <input
              type="checkbox"
              checked={includeAiBriefing}
              onChange={e => setIncludeAiBriefing(e.target.checked)}
              className="w-4 h-4 text-purple-600 rounded bg-slate-900 border-slate-700 accent-purple-500 cursor-pointer"
            />
          </div>

          {/* Automated Scheduler Accordion */}
          <div className="pt-2 border-t border-slate-800">
            <button
              type="button"
              onClick={() => setIsScheduleOpen(!isScheduleOpen)}
              className="w-full flex items-center justify-between text-cyan-400 hover:text-cyan-300 font-semibold cursor-pointer"
            >
              <span className="flex items-center gap-1.5">
                <Clock className="w-4 h-4" />
                <span>{t('إعداد الجدولة التلقائية الدورية (Daily / Weekly / Monthly)', 'Automated Cron Scheduler')}</span>
              </span>
              <span>{isScheduleOpen ? '▲' : '▼'}</span>
            </button>

            {isScheduleOpen && (
              <div className="mt-3 p-4 rounded-2xl bg-slate-950 border border-slate-800 space-y-3">
                <div className="flex items-center gap-3">
                  {(['DAILY', 'WEEKLY', 'MONTHLY'] as const).map(p => (
                    <label key={p} className="flex items-center gap-1.5 cursor-pointer">
                      <input
                        type="radio"
                        name="cronPeriod"
                        checked={scheduleCron === p}
                        onChange={() => setScheduleCron(p)}
                        className="text-cyan-500"
                      />
                      <span>{p === 'DAILY' ? 'يومي (Daily)' : p === 'WEEKLY' ? 'أسبوعي (Weekly)' : 'شهري (Monthly)'}</span>
                    </label>
                  ))}
                </div>

                <div>
                  <label className="text-[11px] text-slate-400 block mb-1">
                    {t('البريد الإلكتروني للمستلمين:', 'Recipient Email Addresses:')}
                  </label>
                  <input
                    type="email"
                    value={scheduleEmails}
                    onChange={e => setScheduleEmails(e.target.value)}
                    className="w-full px-3 py-1.5 rounded-xl bg-slate-900 border border-slate-700 text-slate-200 text-xs focus:outline-none focus:border-cyan-500"
                  />
                </div>

                <button
                  type="button"
                  onClick={handleSaveSchedule}
                  className="px-4 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-cyan-300 border border-cyan-800/60 font-semibold text-xs transition cursor-pointer"
                >
                  {t('حفظ جدول الإرسال الآلي', 'Save Automated Schedule')}
                </button>
              </div>
            )}
          </div>

          {/* Export Action Button */}
          <button
            type="button"
            disabled={isExporting}
            onClick={handleExport}
            className="w-full py-3 rounded-2xl bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white font-bold text-xs transition shadow-lg shadow-cyan-500/20 flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
          >
            {isExporting ? (
              <span>{t('جاري تجميع البيانات وتجهيز التقرير...', 'Compiling and certifying report...')}</span>
            ) : (
              <>
                <Download className="w-4 h-4" />
                <span>{t(`تصدير وتحميل تقرير ${reportCategory} بصيغة ${format}`, `Export & Download ${reportCategory} Report (${format})`)}</span>
              </>
            )}
          </button>

          {exportedNotice && (
            <div className="p-3 rounded-xl bg-emerald-950/80 border border-emerald-700 text-emerald-300 text-xs text-center font-medium">
              {exportedNotice}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
